Time::DATE_FORMATS[:slashes] = '%m/%d/%Y'
Time::DATE_FORMATS[:reversed_slashes] = '%Y/%m/%d'
Time::DATE_FORMATS[:datetime] = '%B %-d, %Y at %-l:%M %p'
Time::DATE_FORMATS[:dateonly] = '%B %-d, %Y'
Time::DATE_FORMATS[:ampmtime] = '%-l:%M %p'
Time::DATE_FORMATS[:ampmhour] = '%-l %p'
